# frozen_string_literal: true

source "https://rubygems.org"

gem 'pg'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rspec'
gem 'capybara'

group :development, :test do
  gem "rubocop", "1.20"
end

# gem "rails"
